### ISSUE TITLE
problems with "customer email" option

### ISSUE THREAD

**Issue by xmodpt** [Softdiscover/ZigaForm-PHP-Form-Builder-Lite#3]
Hello everyone

I have downloaded the latest github version and install it on Win7 machine with xampp.

Followed all the youtube videos and the "sending" email is not working for me.
I config the send from email to my test gmail mail address and tested the form, got the Submit OK after sending but no email got to my mailbox.
And whenever i activate the option to send a copy to the "customer" i get an error message

                            " Error! Form was not submitted. " 

And no email to me or the customer.

Can you guys help ?

King regards
Xmodpt

**Comment by larangin** [comment]
sorry for late response.  if there is not mail notification, your mail service could be not working on your web host, you can use smtp settings, you can use mailtrap for testing: https://mailtrap.io/, it provides smtp credentials for you to test
