### ISSUE TITLE
Sending the form does not work

### ISSUE THREAD

**Issue by shirleyzig** [Softdiscover/ZigaForm-PHP-Form-Builder-Lite#5]
Hello together
The submission of my form at https://www.reunion.certifiedfirst.ch/reunion-form.html
unfortunately doesn't work, as soon as I click on Inscrire it hangs and doesen't continue. 
Can anyone help me with this?

**Comment by larangin** [comment]
As we haven’t received any updates on this issue in a while, we’ll go ahead and close it for now. If you have additional details or further questions, please feel free to reopen the issue or start a new thread. Thank you!
